### ISSUE TITLE
missing web page

### ISSUE THREAD

**Issue by marksherman** [oplS15projects/WOLFRACKET#4]
Readme.md must be updated to reflect the requirements here: 

https://github.com/oplS15projects/FP7-webpage

I'm grading them now, but I'll swing back to yours in a bit.

**Comment by josefflores** [comment]
Thanks, but I have not gotten to do this because I am trying to get the
form working for the demo. The button does not submit my form but rather
resets the page. The HTML renders correctly but the js include is being
finicky. I don't know if its a racket thing or if it is something else.

**Comment by josefflores** [comment]
https://github.com/oplS15projects/WOLFRACKET/releases/tag/M3
